apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-report-hpa-helm
  labels:
    app: backend-report-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-report
  minReplicas: {{ .Values.replicas.min }}
  maxReplicas: {{ .Values.replicas.max }}
  targetCPUUtilizationPercentage: {{ .Values.targetcpuutilizationpercentage }}
