---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-uri
  labels:
    app: backend-report
data:
  spring_data_mongodb_uri: bW9uZ29kYjovL3N0ZC0wMzAtMTg6VGVzdHVzcjEyMzRAcmMxYS0zbmI3cDdqc21idXA2Y3J0Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAzMC0xOD90bHM9dHJ1ZQ==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsiYXV0aCI6ImMzUmtMVEF6TUMweE9EcGxNek15ZVRkblRBPT0ifX19