stages:
  - downstream

frontend:
  stage: downstream
  trigger:
    include:
      - local: '/frontend/.gitlab-ci.yml'
    strategy: depend
  only:
    changes:
      - frontend/**/*

backend:
  stage: downstream
  trigger:
    include:
      - local: '/backend/.gitlab-ci.yml'
    strategy: depend
  only:
    changes:
      - backend/**/*

backend-report:
  stage: downstream
  trigger:
    include:
      - local: '/backend-report/.gitlab-ci.yml'
    strategy: depend
  only:
    changes:
      - backend-report/**/* 

helm-release:
  stage: downstream
  trigger:
    include:
      - local: '/release-and-deploy/.gitlab-ci.yml'
    strategy: depend
  needs:
    - frontend
    - backend
    - backend-report
