apiVersion: v2
appVersion: latest
dependencies:
- name: backend
  repository: ""
  version: 1.0.1624845
- name: backend-report
  repository: ""
  version: 1.0.1624845
- name: frontend
  repository: ""
  version: 1.0.1624845
description: Sausage-Store Helm Chart
icon: file://sausage-store.jpg
name: sausage-store
type: application
version: 1.0.1624845
