apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsiYXV0aCI6ImMzUmtMVEF6TUMweE9EcGxNek15ZVRkblRBPT0ifX19
  # Example:
  # password: {{ .Values.password | b64enc }}