  imageName: ""
  imageTag: ""
  replicas: ""
  port: ""
  resources:
    requests:
      memory: ""
      cpu: ""
    limits:
      memory: ""
      cpu: ""
  path: /
  initialDelaySeconds: 15
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 6
  periodSeconds: 30