- name: Шаблонизация конфига управляет настройками приложения с помощью переменных
  template:
    src: sausage-store.conf.j2
    dest: /etc/nginx/conf.d/sausage-store.conf
- name: Перечитываем конфигурацию systemd
  systemd:
    daemon_reload: yes
- name: всё готово - запускаем!
  service:
    name: nginx
    state: started