- name: Шаблонизация конфига управляет настройками приложения с помощью переменных
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/sausage.conf
- name: Перечитываем конфигурацию systemd
  systemd:
    daemon_reload: yes
- name: всё готово - запускаем!
  service:
    name: nginx
    state: running