apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-frontend
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sausage-store

spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: "{{ .Values.global.repository }}/{{ .Values.imageName }}:{{ .Values.imageTag }}"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: docker-sock-helm
          mountPath: /tmp/docker.sock
          readOnly: true
        ports:
          - name: frontend
            containerPort: {{ .Values.port }}
        livenessProbe:
          httpGet:
            path: {{ .Values.path }}
            port: {{ .Values.port }}
          initialDelaySeconds: {{ .Values.initialDelaySecond }}
          timeoutSeconds: {{ .Values.timeoutSeconds }}
          successThreshold: {{ .Values.successThreshold }}
          failureThreshold: {{ .Values.failureThreshold }}
          periodSeconds: {{ .Values.periodSeconds }}
        
        resources:
          {{ toYaml .Values.resources | nindent 12 }}
          
      volumes:
        - name: docker-sock-helm
          hostPath:
            path: /var/run/docker.sock
        - name: nginx-conf
          configMap:
            name: nginx-conf-helm
            items:
              - key: nginx.conf
                path: nginx.conf

      imagePullSecrets:
        - name: docker-config-secret

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - frontend
                topologyKey: "kubernetes.io/hostname"
