apiVersion: v1
kind: Service
metadata:
  name: frontend-helm
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
  - name: frontend
    protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}