apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: backend
data:
  vault_token: aHZzLkNBRVNJUFRic0RXUmFCckhTVlVyek4taTFTWE9ZNTJNTGZLaVQ3VXRGRHNKRFpnSEdoNEtIR2gyY3k1VU0yUXhSVU42YnpkNU5GTTRkMDA1UTNGcE1UVlZaMm8=
type: Opaque
# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsiYXV0aCI6ImMzUmtMVEF6TUMweE9EcGxNek15ZVRkblRBPT0ifX19
type: kubernetes.io/dockerconfigjson