---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: backend
data:
  vault_token: aHZzLkNBRVNJUFRic0RXUmFCckhTVlVyek4taTFTWE9ZNTJNTGZLaVQ3VXRGRHNKRFpnSEdoNEtIR2gyY3k1VU0yUXhSVU42YnpkNU5GTTRkMDA1UTNGcE1UVlZaMm8=
type: Opaque
