- name: Creates directory
  ansible.builtin.file:
    path: "{{backend_working_directory}}"
    state: directory
- name: Creates directory
  ansible.builtin.file:
    path: "{{backend_report_directory}}"
    state: directory
- name: Скачивание артефакта из Nexus
  get_url:
    url: "{{nexus_url}}/repository/{{nexus_repository_backend_name}}/com/yandex/practicum/devops/{{artifact_name}}/{{version}}/sausage-store-{{version}}.jar"
    dest: "{{backend_working_directory}}"
    mode: '0755'
    owner: "{{ backend_service_user }}"
    group: "{{ backend_service_user }}"
    username: "{{ nexus_repo_user }}"
    password: "{{ nexus_repo_pass }}"