- name: Создаем юзера бекед
  import_tasks: create_backend_user.yml
  
- name: Качаем бекенд
  import_tasks: download_backend.yml

- name: Устанавливаем ждк
  import_tasks: installs.yml
  
- name: ЗАпускаем сервисы
  import_tasks: create_backend_services.yml