  imageName: "sausage-backend-report"
  imageTag: "519eb352b5563c70c587454d78409ae2e7edf641"
  replicas:
    min: 1
    max: 5
  port: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "100m"
  targetcpuutilizationpercentage: 75
  path: /actuator/health
  initialDelaySeconds: 95
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 6
  periodSeconds: 30