  imageName: ""
  imageTag: ""
  replicas:
    min: 1
    max: 5
  port: ""
  resources:
    requests:
      memory: ""
      cpu: ""
    limits:
      memory: ""
      cpu: ""
  targetcpuutilizationpercentage: 75
  path: /actuator/health
  initialDelaySeconds: 95
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 6
  periodSeconds: 30