---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-backend-report
  namespace: default 
  labels:
    app: backend-report
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-report
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 75
  # - type: Resource
    # resource:
        # name: memory
        # target:
          # type: Utilization
          # averageValue: 800Mi