apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
      - name: backend-report
        image: gitlab.praktikum-services.ru:5050/std-030-18/sausage-store/sausage-backend-report:02f7cdf3bf9551aac80cb46a93428ad6982f5d46
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 6
          periodSeconds: 30
        env:
          - name: PORT
            value: "8080"
          - name: SPRING_DATA_MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb-uri
                key: spring_data_mongodb_uri
      imagePullSecrets:
        - name: docker-config-secret